openapi: 3.0.0
info:
  title: Plant Search API
  version: 1.0.1
  description: An API to search plants native to Oregon based on various characteristics.
servers:
  - url: PLUGIN_HOSTNAME
paths:

  /detail/{tid}:
    get:
      operationId: getPlantDetail
      summary: Get details of a certain plant
      description: Returns a payload of details for a single plant.
      parameters:
        - name: tid
          in: path
          description: The tid (taxon id) of the plant to get details for.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  tid:
                    type: integer
                    description: The taxonomic identifier (tid) of the taxa.
                  sciname:
                    type: string
                    description: The scientific name of the taxa.
                  author:
                    type: string
                    description: The author of the taxa.
                  parentTid:
                    type: integer
                    description: The taxonomic identifier (tid) of the parent taxa.
                  rankId:
                    type: integer
                    description: The rank identifier (rankId) of the taxa.
                  descriptions:
                    type: array
                    items:
                      type: object
                      properties:
                        caption:
                          type: string
                        source:
                          type: string
                        url:
                          type: string
                        desc:
                          type: object
                          additionalProperties:
                            type: string
                  gardenDescription:
                    type: string
                  gardenId:
                    type: integer
                  imagesBasis:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: string
                  vernacular:
                    type: object
                    properties:
                      basename:
                        type: string
                      names:
                        type: array
                        items:
                          type: string
                  synonyms:
                    type: array
                    items:
                      type: object
                      properties:
                        sciname:
                          type: string
                        author:
                          type: string
                        tid:
                          type: integer
                  ambiguousSynonyms:
                    type: array
                    items:
                      type: string
                  taxalinks:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                        title:
                          type: string
                  rarePlantFactSheet:
                    type: string
                  origin:
                    type: string
                  family:
                    type: string
                  characteristics:
                    type: object
                    properties:
                    # Add properties as needed for characteristics
                  spp:
                    type: array
                    items:
                      type: string
                  checklists:
                    type: array
                    items:
                      type: integer

  /search:
    post:
      operationId: searchPlants
      summary: Search plants based on various characteristics
      description: Returns a list of plants that match the given characteristics.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                search:
                  type: string
                  description: Search plants by name.
                sunlight:
                  type: string
                  enum: ["", "680-1", "680-2", "680-3"]
                  description: >
                    Sunlight conditions:
                    - 680-1: Sun
                    - 680-2: Part-Shade
                    - 680-3: Full-Shade
                moisture:
                  type: string
                  enum: ["", "683-1", "683-2", "683-3"]
                  description: >
                    Moisture conditions:
                    - 683-1: Dry
                    - 683-2: Moderate
                    - 683-3: Wet
                height:
                  type: string
                  description: Height range in feet (e.g., "45-50+")
                width:
                  type: string
                  description: Width range in feet (e.g., "0-80")
                flower_color:
                  type: array
                  items:
                    type: string
                    enum: ["612-5", "612-9", "612-2", "612-7", "612-10", "612-1", "612-8", "612-4", "612-6", "612-3", "612-11"]
                  description: >
                    Flower colors:
                    - 612-5: white
                    - 612-9: pink
                    - 612-2: red
                    - 612-7: orange
                    - 612-10: yellow
                    - 612-1: green
                    - 612-8: blue
                    - 612-4: purple
                    - 612-6: brown
                    - 612-3: black
                    - 612-11: flowers diminutive
                bloom_months:
                  type: array
                  items:
                    type: string
                    enum: ["165-1", "165-2", "165-3", "165-4", "165-5", "165-6", "165-7", "165-8", "165-9", "165-10", "165-11", "165-12"]
                  description: >
                    Bloom months:
                    - 165-1: January
                    - 165-2: February
                    - 165-3: March
                    - 165-4: April
                    - 165-5: May
                    - 165-6: June
                    - 165-7: July
                    - 165-8: August
                    - 165-9: September
                    - 165-10: October
                    - 165-11: November
                    - 165-12: December
                wildlife_support:
                  type: array
                  items:
                    type: string
                    enum: ["685-2", "685-3", "685-1", "685-5", "685-6"]
                  description: >
                    Wildlife support:
                    - 685-2: bees and other insect pollinators
                    - 685-3: beneficial insects/pest eating insects
                    - 685-1: adult butterflies/nectar source
                    - 685-5: caterpillar host plant/larval food source
                    - 685-6: hummingbirds
                lifespan:
                  type: array
                  items:
                    type: string
                    enum: ["136-1", "136-2", "136-3"]
                  description: >
                    Lifespan:
                      - 136-1: annual
                      - 136-2: biennial
                      - 136-3: perennial
                foliage_type:
                  type: array
                  items:
                    type: string
                    enum: ["100-1", "100-2", "100-3"]
                  description: >
                    Foliage type:
                      - 100-1: deciduous
                      - 100-2: evergreen
                      - 100-3: plants without leaves
                plant_type:
                  type: array
                  items:
                    type: string
                    enum: ["137-1", "137-2", "137-3", "137-4", "137-5", "137-6"]
                  description: >
                    Plant type:
                      - 137-1: herb
                      - 137-2: shrub
                      - 137-3: tree
                      - 137-4: grass or grass-like
                      - 137-5: fern or fern ally
                      - 137-6: vine
                landscape_uses:
                  type: array
                  items:
                    type: string
                    enum: ["679-1", "679-2", "679-8", "679-9", "679-3", "679-4", "679-10", "679-5", "679-6", "679-7"]
                  description: >
                    Landscape uses:
                      - 679-1: clump/tuft-forming
                      - 679-2: erosion control
                      - 679-8: grazing
                      - 679-9: green roof
                      - 679-3: groundcover
                      - 679-4: hedgerow
                      - 679-10: rangeland revegetation
                      - 679-5: screen
                      - 679-6: thicket-forming
                      - 679-7: windbreak
                cultivation_preferences:
                  type: array
                  items:
                    type: string
                    enum: ["767-2", "767-5", "767-6", "767-7", "767-8"]
                  description: >
                    Cultivation preferences:
                      - 767-2: drought tolerant
                      - 767-5: moist soils
                      - 767-6: tolerates constant flooding
                      - 767-7: tolerates seasonal wet
                      - 767-8: well-drained
                behavior:
                  type: array
                  items:
                    type: string
                    enum: ["688-1", "688-2", "688-3", "688-4"]
                  description: >
                    Behavior:
                      - 688-1: bulb or bulb-like structures
                      - 688-2: runners (rhizomes, stolons, etc.)
                      - 688-3: seed
                      - 688-4: spores
                propagation:
                  type: array
                  items:
                    type: string
                    enum: ["740-3", "740-5", "740-7", "740-4", "740-2", "740-1", "740-6"]
                  description: >
                    Propagation:
                      - 740-3: direct- or self-seed
                      - 740-5: seed with stratification
                      - 740-7: seed with scarification
                      - 740-4: seed with both scarification and stratification
                      - 740-2: division/separation
                      - 740-1: cuttings
                      - 740-6: spores
                ease_of_growth:
                  type: array
                  items:
                    type: string
                    enum: ["684-1", "684-2", "684-3"]
                  description: >
                    Ease of growth:
                      - 684-1: easy
                      - 684-2: moderate
                      - 684-3: hard
                ecoregions:
                  type: array
                  items:
                    type: string
                    enum: ["19-1", "19-2", "19-3", "19-4", "19-5", "19-6", "19-7", "19-8", "19-9", "19-10", "19-11"]
                  description: >
                    (Can select multiple)
                    Ecoregions:
                      - 19-1: Basin and Range
                      - 19-2: Blue and Wallowa Mountains
                      - 19-3: Cascades
                      - 19-4: Coast Range
                      - 19-5: Columbia Basin
                      - 19-6: Eastern Cascade Slopes and Foothills
                      - 19-7: Estuarine Coast
                      - 19-8: Lava Plains
                      - 19-9: Owyhee Uplands
                      - 19-10: Siskiyou Mountains
                      - 19-11: Willamette Valley
                habitat:
                  type: array
                  items:
                    type: string
                    enum: ["163-1", "163-2", "163-3", "163-4", "163-5", "163-6", "163-7", "163-8", "163-9", "163-10", "163-11", "163-12", "163-13"]
                  description: >
                    Habitat:
                      - 163-1: alpine
                      - 163-2: brackish water
                      - 163-3: flowing water
                      - 163-4: forest
                      - 163-5: freshwater wetlands
                      - 163-6: grassland or meadow
                      - 163-7: oak savannah
                      - 163-8: bare or rock-covered ground
                      - 163-9: saltwater
                      - 163-10: open sandy ground, dunes, or beach
                      - 163-11: shrub, scrub or chaparral
                      - 163-12: freshwater pond or lake
                      - 163-13: disturbed sites

      responses:
        '200':
          description: OK
          content:
            text/csv:
              schema:
                type: string
              example: |
                tid,family,sciname,parenttid,author,imgid,vernacular_basename,vernacular_names,image
                8027,Alismataceae,Sagittaria latifolia,1385,Willd.,23769515,wapato,"wapato,broadleaf arrowhead,duck potato",/imglib/OF_FP/201905/DIG21964_1558125747_tn.jpg